### ISSUE TITLE
Rate-limiting terraform state mv calls

### ISSUE THREAD

**Issue by xanonid** [mbode/terraform-state-mover#4]
For example, with the google terraform provider and remote state, `terraform state mv` could only be called approximately every 2 seconds, otherwise the state cannot be locked anymore due to rate limits by Google APIs.

If there are more than only few renamings, terraform-state-mover could fail because of this. It would be nice if there is either a default rate limit or a flag which allows to delay the terraform calls.

**Comment by mbode** [comment]
Thank you very much! This has been released in [0.3.0](https://github.com/mbode/terraform-state-mover/releases/tag/0.3.0).
